#pragma config(Motor,  port1,            ,             tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,            ,             tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,            ,             tmotorVex393, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	motor[port1] = 100;
	motor[port2] = 100;
	motor[port3] = 100;
	motor[port4] = 100;
	wait10Msec(100);
	motor[port1] = 0;
	motor[port2] = 0;
	motor[port3] = 0;
	motor[port4] = 0;

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
// 1,2,3,4 be drive

task usercontrol()
{
	int rekt[4];
	int leek[4];
	int sss[4];
	int sage[4];
	while (true)
	{
		motor[port1] = vexRT[Ch2];
		motor[port2] = vexRT[Ch2];
		motor[port3] = vexRT[Ch3];
		motor[port4] = vexRT[Ch3];

		rekt[1] = vexRT[Btn5U]*127;
		rekt[2] = vexRT[Btn5D]*-127;
		rekt[3] = rekt[1]+rekt[2];
		motor[port5] = rekt[3];
		motor[port6] = rekt[3];

		leek[1] = vexRT[Btn6U]*127;
		leek[2] = vexRT[Btn6D]*-127;
		leek[3] = leek[1]+leek[2];
		motor[port7] = leek[3];


		sss[1] = vexRT[Btn7U]*127;
		sss[2] = vexRT[Btn7D]*-127;
		sss[3] = sss[1]+sss[2];
		motor[port8] = sss[3];


		sage[1] = vexRT[Btn8U]*127;
		sage[2] = vexRT[Btn8D]*-127;
		sage[3] = sage[1]+sage[2];
		motor[port9] = sage[3];





























	}
}
