#pragma config(Motor,  port1,            ,             tmotorVex393, openLoop)
#pragma config(Motor,  port2,            ,             tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,            ,             tmotorVex393, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,            ,             tmotorVex393, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	motor[port3] = 127;
	motor[port7] = 127;
	wait10Msec(100);
	motor[port3] = 0;
	motor[port7] = 0;
	motor[port6] = 80;
	motor[port8] = 80;
	wait10Msec(100);
	motor[port6] = 0;
	motor[port8] = 0;
	wait10Msec(10);
	motor[port3] = -127;
	motor[port7] = -127;
	wait10Msec(100);
	motor[port3] = 0;
	motor[port7] = 0;
	motor[port6] = -80;
	motor[port8] = -80;
	wait10Msec(200);
	motor[port6] = 0;
	motor[port8] = 0;



	//motor[port2] = 100;
	//motor[port6] = 100;
	//motor[port4] = 100;
	//motor[port8] = 100;
	//wait10Msec(100);
	//motor[port2] = 0;
	//motor[port6] = 0;
	//motor[port4] = 0;
	//motor[port8] = 0;
	//int mek[6];
	//mek[1] = getEncoderForMotor(port2);
	//mek[2] = getEncoderForMotor(port4);
	//mek[3] = getEncoderForMotor(port6);
	//mek[4] = getEncoderForMotor(port8);
	//while(mek[1] <= 10)
	//{
	//	motor[port2] = 120;
	//}

	//wait10Msec(100);

	//while(mek[2] <= 10)
	//{
	//	motor[port4] = 120;
	//}


}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	int leek;
	leek = 0;
	int gib[4];
	int fis[4];
	while(true)
	{
		motor[port2] = vexRT[Ch2];

		motor[port6] = vexRT[Ch2];
		motor[port4] = vexRT[Ch3];
		motor[port8] = vexRT[Ch3];

		if(leek == 1)
		{
			motor[port1] = vexRT[Ch2Xmtr2];
			motor[port10] = vexRT[Ch2Xmtr2];
			motor[port7] = vexRT[Ch2Xmtr2];
			motor[port5] = vexRT[Ch2Xmtr2];
			motor[port3] = vexRT[Ch2Xmtr2];

		}

		if(vexRT[Btn7U] == 1 && leek == 0)
		{
			leek = 1;
		}

		if(vexRT[Btn7U] == 1 && leek == 0)
		{
			leek = 0;
		}

		if(leek == 0)
		{
			gib[1] = vexRT[Btn8U]*127;
			gib[2] = vexRT[Btn8D]*-127;
			gib[3] = gib[1]+gib[2];
			motor[port1] = gib[3];
			motor[port10] = gib[3];
			motor[port7] = gib[3];
			motor[port5] = gib[3];
			motor[port3] = gib[3];
		}
		fis[1] = vexRT[Btn6U]*127;
		fis[2] = vexRT[Btn6D]*-127;
		fis[3] = fis[1]+fis[2];
		motor[port9] = fis[3];
	}
}
